import numpy as np

TRAJECTORIES_N = 256
BRANCHES_N = 256
INITIAL_LENGTH = BRANCHES_N * 2
BRANCH_LENGTH = int(BRANCHES_N / 2)
NOISE_DEPTH = 2
VALUE_ITERATIONS = 1
VALUE_LOSS_LIMIT = 0.0001
DISCOUNT_VALUE = 0.99
TIME_STEP = 0.02
ACTION_BIAS = 18000
ACTION_MAX = 30000
NOISE_COV = np.array(np.diag([ACTION_BIAS,ACTION_BIAS,ACTION_BIAS,ACTION_BIAS]), dtype=np.float32)
NOISE_STDDEV = 0.2
